//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackNight.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venda", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    [System.SerializableAttribute()]
    public partial class Venda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlackNight.ServiceReference.Cliente CdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlackNight.ServiceReference.Evento CdEventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CdVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtVendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlackNight.ServiceReference.Cliente CdCliente {
            get {
                return this.CdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CdClienteField, value) != true)) {
                    this.CdClienteField = value;
                    this.RaisePropertyChanged("CdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlackNight.ServiceReference.Evento CdEvento {
            get {
                return this.CdEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.CdEventoField, value) != true)) {
                    this.CdEventoField = value;
                    this.RaisePropertyChanged("CdEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdVenda {
            get {
                return this.CdVendaField;
            }
            set {
                if ((this.CdVendaField.Equals(value) != true)) {
                    this.CdVendaField = value;
                    this.RaisePropertyChanged("CdVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtVenda {
            get {
                return this.DtVendaField;
            }
            set {
                if ((this.DtVendaField.Equals(value) != true)) {
                    this.DtVendaField = value;
                    this.RaisePropertyChanged("DtVenda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtNascClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NmClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SxClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdCliente {
            get {
                return this.CdClienteField;
            }
            set {
                if ((this.CdClienteField.Equals(value) != true)) {
                    this.CdClienteField = value;
                    this.RaisePropertyChanged("CdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CpfCliente {
            get {
                return this.CpfClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfClienteField, value) != true)) {
                    this.CpfClienteField = value;
                    this.RaisePropertyChanged("CpfCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtNascCliente {
            get {
                return this.DtNascClienteField;
            }
            set {
                if ((this.DtNascClienteField.Equals(value) != true)) {
                    this.DtNascClienteField = value;
                    this.RaisePropertyChanged("DtNascCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCliente {
            get {
                return this.EmailClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailClienteField, value) != true)) {
                    this.EmailClienteField = value;
                    this.RaisePropertyChanged("EmailCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NmCliente {
            get {
                return this.NmClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NmClienteField, value) != true)) {
                    this.NmClienteField = value;
                    this.RaisePropertyChanged("NmCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumCliente {
            get {
                return this.NumClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumClienteField, value) != true)) {
                    this.NumClienteField = value;
                    this.RaisePropertyChanged("NumCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SxCliente {
            get {
                return this.SxClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.SxClienteField, value) != true)) {
                    this.SxClienteField = value;
                    this.RaisePropertyChanged("SxCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evento", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    [System.SerializableAttribute()]
    public partial class Evento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlackNight.ServiceReference.Atracao CdAtracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CdEventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtEventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NmEventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdIngFemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdIngMascField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VlIngFemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VlIngMascField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlackNight.ServiceReference.Atracao CdAtracao {
            get {
                return this.CdAtracaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CdAtracaoField, value) != true)) {
                    this.CdAtracaoField = value;
                    this.RaisePropertyChanged("CdAtracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdEvento {
            get {
                return this.CdEventoField;
            }
            set {
                if ((this.CdEventoField.Equals(value) != true)) {
                    this.CdEventoField = value;
                    this.RaisePropertyChanged("CdEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtEvento {
            get {
                return this.DtEventoField;
            }
            set {
                if ((this.DtEventoField.Equals(value) != true)) {
                    this.DtEventoField = value;
                    this.RaisePropertyChanged("DtEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NmEvento {
            get {
                return this.NmEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.NmEventoField, value) != true)) {
                    this.NmEventoField = value;
                    this.RaisePropertyChanged("NmEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdIngFem {
            get {
                return this.QtdIngFemField;
            }
            set {
                if ((this.QtdIngFemField.Equals(value) != true)) {
                    this.QtdIngFemField = value;
                    this.RaisePropertyChanged("QtdIngFem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdIngMasc {
            get {
                return this.QtdIngMascField;
            }
            set {
                if ((this.QtdIngMascField.Equals(value) != true)) {
                    this.QtdIngMascField = value;
                    this.RaisePropertyChanged("QtdIngMasc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VlIngFem {
            get {
                return this.VlIngFemField;
            }
            set {
                if ((this.VlIngFemField.Equals(value) != true)) {
                    this.VlIngFemField = value;
                    this.RaisePropertyChanged("VlIngFem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VlIngMasc {
            get {
                return this.VlIngMascField;
            }
            set {
                if ((this.VlIngMascField.Equals(value) != true)) {
                    this.VlIngMascField = value;
                    this.RaisePropertyChanged("VlIngMasc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Atracao", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    [System.SerializableAttribute()]
    public partial class Atracao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CdAtracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NmAtracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumAtracaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdAtracao {
            get {
                return this.CdAtracaoField;
            }
            set {
                if ((this.CdAtracaoField.Equals(value) != true)) {
                    this.CdAtracaoField = value;
                    this.RaisePropertyChanged("CdAtracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NmAtracao {
            get {
                return this.NmAtracaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NmAtracaoField, value) != true)) {
                    this.NmAtracaoField = value;
                    this.RaisePropertyChanged("NmAtracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumAtracao {
            get {
                return this.NumAtracaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumAtracaoField, value) != true)) {
                    this.NumAtracaoField = value;
                    this.RaisePropertyChanged("NumAtracao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormaPagto", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    [System.SerializableAttribute()]
    public partial class FormaPagto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CdFormaPagtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescFormaPagtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdFormaPagto {
            get {
                return this.CdFormaPagtoField;
            }
            set {
                if ((this.CdFormaPagtoField.Equals(value) != true)) {
                    this.CdFormaPagtoField = value;
                    this.RaisePropertyChanged("CdFormaPagto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescFormaPagto {
            get {
                return this.DescFormaPagtoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescFormaPagtoField, value) != true)) {
                    this.DescFormaPagtoField = value;
                    this.RaisePropertyChanged("DescFormaPagto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormaPagtoVenda", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    [System.SerializableAttribute()]
    public partial class FormaPagtoVenda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlackNight.ServiceReference.Evento CdEventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlackNight.ServiceReference.FormaPagto CdFormaPagtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VlPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlackNight.ServiceReference.Evento CdEvento {
            get {
                return this.CdEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.CdEventoField, value) != true)) {
                    this.CdEventoField = value;
                    this.RaisePropertyChanged("CdEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlackNight.ServiceReference.FormaPagto CdFormaPagto {
            get {
                return this.CdFormaPagtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CdFormaPagtoField, value) != true)) {
                    this.CdFormaPagtoField = value;
                    this.RaisePropertyChanged("CdFormaPagto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlPago {
            get {
                return this.VlPagoField;
            }
            set {
                if ((this.VlPagoField.Equals(value) != true)) {
                    this.VlPagoField = value;
                    this.RaisePropertyChanged("VlPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RitmoEvento", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    [System.SerializableAttribute()]
    public partial class RitmoEvento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlackNight.ServiceReference.Evento CdEventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlackNight.ServiceReference.Ritmo CdRitmoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlackNight.ServiceReference.Evento CdEvento {
            get {
                return this.CdEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.CdEventoField, value) != true)) {
                    this.CdEventoField = value;
                    this.RaisePropertyChanged("CdEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlackNight.ServiceReference.Ritmo CdRitmo {
            get {
                return this.CdRitmoField;
            }
            set {
                if ((object.ReferenceEquals(this.CdRitmoField, value) != true)) {
                    this.CdRitmoField = value;
                    this.RaisePropertyChanged("CdRitmo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ritmo", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    [System.SerializableAttribute()]
    public partial class Ritmo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CdRitmoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NmRitmoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdRitmo {
            get {
                return this.CdRitmoField;
            }
            set {
                if ((this.CdRitmoField.Equals(value) != true)) {
                    this.CdRitmoField = value;
                    this.RaisePropertyChanged("CdRitmo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NmRitmo {
            get {
                return this.NmRitmoField;
            }
            set {
                if ((object.ReferenceEquals(this.NmRitmoField, value) != true)) {
                    this.NmRitmoField = value;
                    this.RaisePropertyChanged("NmRitmo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovaVenda", ReplyAction="http://tempuri.org/IService1/NovaVendaResponse")]
        void NovaVenda(BlackNight.ServiceReference.Venda v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovaVenda", ReplyAction="http://tempuri.org/IService1/NovaVendaResponse")]
        System.Threading.Tasks.Task NovaVendaAsync(BlackNight.ServiceReference.Venda v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarVendas", ReplyAction="http://tempuri.org/IService1/ListarVendasResponse")]
        BlackNight.ServiceReference.Venda[] ListarVendas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarVendas", ReplyAction="http://tempuri.org/IService1/ListarVendasResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Venda[]> ListarVendasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProcurarId", ReplyAction="http://tempuri.org/IService1/ProcurarIdResponse")]
        BlackNight.ServiceReference.Venda ProcurarId(int idCliente, int idEvento, System.DateTime dtEvento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProcurarId", ReplyAction="http://tempuri.org/IService1/ProcurarIdResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Venda> ProcurarIdAsync(int idCliente, int idEvento, System.DateTime dtEvento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarVenda", ReplyAction="http://tempuri.org/IService1/PesquisarVendaResponse")]
        BlackNight.ServiceReference.Venda PesquisarVenda(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarVenda", ReplyAction="http://tempuri.org/IService1/PesquisarVendaResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Venda> PesquisarVendaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovoCliente", ReplyAction="http://tempuri.org/IService1/NovoClienteResponse")]
        void NovoCliente(BlackNight.ServiceReference.Cliente c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovoCliente", ReplyAction="http://tempuri.org/IService1/NovoClienteResponse")]
        System.Threading.Tasks.Task NovoClienteAsync(BlackNight.ServiceReference.Cliente c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarCliente", ReplyAction="http://tempuri.org/IService1/PesquisarClienteResponse")]
        BlackNight.ServiceReference.Cliente PesquisarCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarCliente", ReplyAction="http://tempuri.org/IService1/PesquisarClienteResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Cliente> PesquisarClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarClientes", ReplyAction="http://tempuri.org/IService1/ListarClientesResponse")]
        BlackNight.ServiceReference.Cliente[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarClientes", ReplyAction="http://tempuri.org/IService1/ListarClientesResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Cliente[]> ListarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirCliente", ReplyAction="http://tempuri.org/IService1/ExcluirClienteResponse")]
        void ExcluirCliente(BlackNight.ServiceReference.Cliente c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirCliente", ReplyAction="http://tempuri.org/IService1/ExcluirClienteResponse")]
        System.Threading.Tasks.Task ExcluirClienteAsync(BlackNight.ServiceReference.Cliente c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovoEvento", ReplyAction="http://tempuri.org/IService1/NovoEventoResponse")]
        void NovoEvento(BlackNight.ServiceReference.Evento ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovoEvento", ReplyAction="http://tempuri.org/IService1/NovoEventoResponse")]
        System.Threading.Tasks.Task NovoEventoAsync(BlackNight.ServiceReference.Evento ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarEventos", ReplyAction="http://tempuri.org/IService1/ListarEventosResponse")]
        BlackNight.ServiceReference.Evento[] ListarEventos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarEventos", ReplyAction="http://tempuri.org/IService1/ListarEventosResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Evento[]> ListarEventosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirEvento", ReplyAction="http://tempuri.org/IService1/ExcluirEventoResponse")]
        void ExcluirEvento(BlackNight.ServiceReference.Evento ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirEvento", ReplyAction="http://tempuri.org/IService1/ExcluirEventoResponse")]
        System.Threading.Tasks.Task ExcluirEventoAsync(BlackNight.ServiceReference.Evento ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarEvento", ReplyAction="http://tempuri.org/IService1/PesquisarEventoResponse")]
        BlackNight.ServiceReference.Evento PesquisarEvento(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarEvento", ReplyAction="http://tempuri.org/IService1/PesquisarEventoResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Evento> PesquisarEventoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarPreco", ReplyAction="http://tempuri.org/IService1/PesquisarPrecoResponse")]
        BlackNight.ServiceReference.Evento PesquisarPreco(int id, string tipoIngresso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarPreco", ReplyAction="http://tempuri.org/IService1/PesquisarPrecoResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Evento> PesquisarPrecoAsync(int id, string tipoIngresso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarHoraDoEvento", ReplyAction="http://tempuri.org/IService1/ListarHoraDoEventoResponse")]
        System.DateTime ListarHoraDoEvento(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarHoraDoEvento", ReplyAction="http://tempuri.org/IService1/ListarHoraDoEventoResponse")]
        System.Threading.Tasks.Task<System.DateTime> ListarHoraDoEventoAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovaFormaPagto", ReplyAction="http://tempuri.org/IService1/NovaFormaPagtoResponse")]
        void NovaFormaPagto(BlackNight.ServiceReference.FormaPagto fp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovaFormaPagto", ReplyAction="http://tempuri.org/IService1/NovaFormaPagtoResponse")]
        System.Threading.Tasks.Task NovaFormaPagtoAsync(BlackNight.ServiceReference.FormaPagto fp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarFormaPagto", ReplyAction="http://tempuri.org/IService1/ListarFormaPagtoResponse")]
        BlackNight.ServiceReference.FormaPagto[] ListarFormaPagto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarFormaPagto", ReplyAction="http://tempuri.org/IService1/ListarFormaPagtoResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.FormaPagto[]> ListarFormaPagtoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarFormaPagtoID", ReplyAction="http://tempuri.org/IService1/PesquisarFormaPagtoIDResponse")]
        BlackNight.ServiceReference.FormaPagto PesquisarFormaPagtoID(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarFormaPagtoID", ReplyAction="http://tempuri.org/IService1/PesquisarFormaPagtoIDResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.FormaPagto> PesquisarFormaPagtoIDAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarFormaPagto", ReplyAction="http://tempuri.org/IService1/PesquisarFormaPagtoResponse")]
        BlackNight.ServiceReference.FormaPagto PesquisarFormaPagto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarFormaPagto", ReplyAction="http://tempuri.org/IService1/PesquisarFormaPagtoResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.FormaPagto> PesquisarFormaPagtoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovaFormaPagtoVenda", ReplyAction="http://tempuri.org/IService1/NovaFormaPagtoVendaResponse")]
        void NovaFormaPagtoVenda(BlackNight.ServiceReference.FormaPagtoVenda fpv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovaFormaPagtoVenda", ReplyAction="http://tempuri.org/IService1/NovaFormaPagtoVendaResponse")]
        System.Threading.Tasks.Task NovaFormaPagtoVendaAsync(BlackNight.ServiceReference.FormaPagtoVenda fpv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarFormaPagtoVenda", ReplyAction="http://tempuri.org/IService1/ListarFormaPagtoVendaResponse")]
        BlackNight.ServiceReference.FormaPagtoVenda[] ListarFormaPagtoVenda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarFormaPagtoVenda", ReplyAction="http://tempuri.org/IService1/ListarFormaPagtoVendaResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.FormaPagtoVenda[]> ListarFormaPagtoVendaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarFormaPagtoVenda", ReplyAction="http://tempuri.org/IService1/PesquisarFormaPagtoVendaResponse")]
        BlackNight.ServiceReference.FormaPagtoVenda PesquisarFormaPagtoVenda(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarFormaPagtoVenda", ReplyAction="http://tempuri.org/IService1/PesquisarFormaPagtoVendaResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.FormaPagtoVenda> PesquisarFormaPagtoVendaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovaAtracao", ReplyAction="http://tempuri.org/IService1/NovaAtracaoResponse")]
        void NovaAtracao(BlackNight.ServiceReference.Atracao a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovaAtracao", ReplyAction="http://tempuri.org/IService1/NovaAtracaoResponse")]
        System.Threading.Tasks.Task NovaAtracaoAsync(BlackNight.ServiceReference.Atracao a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarAtracao", ReplyAction="http://tempuri.org/IService1/PesquisarAtracaoResponse")]
        BlackNight.ServiceReference.Atracao PesquisarAtracao(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarAtracao", ReplyAction="http://tempuri.org/IService1/PesquisarAtracaoResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Atracao> PesquisarAtracaoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarAtracoes", ReplyAction="http://tempuri.org/IService1/ListarAtracoesResponse")]
        BlackNight.ServiceReference.Atracao[] ListarAtracoes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarAtracoes", ReplyAction="http://tempuri.org/IService1/ListarAtracoesResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Atracao[]> ListarAtracoesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovoRitmoEvento", ReplyAction="http://tempuri.org/IService1/NovoRitmoEventoResponse")]
        void NovoRitmoEvento(BlackNight.ServiceReference.RitmoEvento re);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovoRitmoEvento", ReplyAction="http://tempuri.org/IService1/NovoRitmoEventoResponse")]
        System.Threading.Tasks.Task NovoRitmoEventoAsync(BlackNight.ServiceReference.RitmoEvento re);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarRitmoEvento", ReplyAction="http://tempuri.org/IService1/PesquisarRitmoEventoResponse")]
        BlackNight.ServiceReference.RitmoEvento PesquisarRitmoEvento(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarRitmoEvento", ReplyAction="http://tempuri.org/IService1/PesquisarRitmoEventoResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.RitmoEvento> PesquisarRitmoEventoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovoRitmo", ReplyAction="http://tempuri.org/IService1/NovoRitmoResponse")]
        void NovoRitmo(BlackNight.ServiceReference.Ritmo r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NovoRitmo", ReplyAction="http://tempuri.org/IService1/NovoRitmoResponse")]
        System.Threading.Tasks.Task NovoRitmoAsync(BlackNight.ServiceReference.Ritmo r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarRitmo", ReplyAction="http://tempuri.org/IService1/PesquisarRitmoResponse")]
        BlackNight.ServiceReference.Ritmo PesquisarRitmo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PesquisarRitmo", ReplyAction="http://tempuri.org/IService1/PesquisarRitmoResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Ritmo> PesquisarRitmoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarRitmos", ReplyAction="http://tempuri.org/IService1/ListarRitmosResponse")]
        BlackNight.ServiceReference.Ritmo[] ListarRitmos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarRitmos", ReplyAction="http://tempuri.org/IService1/ListarRitmosResponse")]
        System.Threading.Tasks.Task<BlackNight.ServiceReference.Ritmo[]> ListarRitmosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirRitmo", ReplyAction="http://tempuri.org/IService1/ExcluirRitmoResponse")]
        void ExcluirRitmo(BlackNight.ServiceReference.Ritmo r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirRitmo", ReplyAction="http://tempuri.org/IService1/ExcluirRitmoResponse")]
        System.Threading.Tasks.Task ExcluirRitmoAsync(BlackNight.ServiceReference.Ritmo r);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BlackNight.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BlackNight.ServiceReference.IService1>, BlackNight.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NovaVenda(BlackNight.ServiceReference.Venda v) {
            base.Channel.NovaVenda(v);
        }
        
        public System.Threading.Tasks.Task NovaVendaAsync(BlackNight.ServiceReference.Venda v) {
            return base.Channel.NovaVendaAsync(v);
        }
        
        public BlackNight.ServiceReference.Venda[] ListarVendas() {
            return base.Channel.ListarVendas();
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Venda[]> ListarVendasAsync() {
            return base.Channel.ListarVendasAsync();
        }
        
        public BlackNight.ServiceReference.Venda ProcurarId(int idCliente, int idEvento, System.DateTime dtEvento) {
            return base.Channel.ProcurarId(idCliente, idEvento, dtEvento);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Venda> ProcurarIdAsync(int idCliente, int idEvento, System.DateTime dtEvento) {
            return base.Channel.ProcurarIdAsync(idCliente, idEvento, dtEvento);
        }
        
        public BlackNight.ServiceReference.Venda PesquisarVenda(int id) {
            return base.Channel.PesquisarVenda(id);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Venda> PesquisarVendaAsync(int id) {
            return base.Channel.PesquisarVendaAsync(id);
        }
        
        public void NovoCliente(BlackNight.ServiceReference.Cliente c) {
            base.Channel.NovoCliente(c);
        }
        
        public System.Threading.Tasks.Task NovoClienteAsync(BlackNight.ServiceReference.Cliente c) {
            return base.Channel.NovoClienteAsync(c);
        }
        
        public BlackNight.ServiceReference.Cliente PesquisarCliente(int id) {
            return base.Channel.PesquisarCliente(id);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Cliente> PesquisarClienteAsync(int id) {
            return base.Channel.PesquisarClienteAsync(id);
        }
        
        public BlackNight.ServiceReference.Cliente[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Cliente[]> ListarClientesAsync() {
            return base.Channel.ListarClientesAsync();
        }
        
        public void ExcluirCliente(BlackNight.ServiceReference.Cliente c) {
            base.Channel.ExcluirCliente(c);
        }
        
        public System.Threading.Tasks.Task ExcluirClienteAsync(BlackNight.ServiceReference.Cliente c) {
            return base.Channel.ExcluirClienteAsync(c);
        }
        
        public void NovoEvento(BlackNight.ServiceReference.Evento ev) {
            base.Channel.NovoEvento(ev);
        }
        
        public System.Threading.Tasks.Task NovoEventoAsync(BlackNight.ServiceReference.Evento ev) {
            return base.Channel.NovoEventoAsync(ev);
        }
        
        public BlackNight.ServiceReference.Evento[] ListarEventos() {
            return base.Channel.ListarEventos();
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Evento[]> ListarEventosAsync() {
            return base.Channel.ListarEventosAsync();
        }
        
        public void ExcluirEvento(BlackNight.ServiceReference.Evento ev) {
            base.Channel.ExcluirEvento(ev);
        }
        
        public System.Threading.Tasks.Task ExcluirEventoAsync(BlackNight.ServiceReference.Evento ev) {
            return base.Channel.ExcluirEventoAsync(ev);
        }
        
        public BlackNight.ServiceReference.Evento PesquisarEvento(int id) {
            return base.Channel.PesquisarEvento(id);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Evento> PesquisarEventoAsync(int id) {
            return base.Channel.PesquisarEventoAsync(id);
        }
        
        public BlackNight.ServiceReference.Evento PesquisarPreco(int id, string tipoIngresso) {
            return base.Channel.PesquisarPreco(id, tipoIngresso);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Evento> PesquisarPrecoAsync(int id, string tipoIngresso) {
            return base.Channel.PesquisarPrecoAsync(id, tipoIngresso);
        }
        
        public System.DateTime ListarHoraDoEvento(string nome) {
            return base.Channel.ListarHoraDoEvento(nome);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> ListarHoraDoEventoAsync(string nome) {
            return base.Channel.ListarHoraDoEventoAsync(nome);
        }
        
        public void NovaFormaPagto(BlackNight.ServiceReference.FormaPagto fp) {
            base.Channel.NovaFormaPagto(fp);
        }
        
        public System.Threading.Tasks.Task NovaFormaPagtoAsync(BlackNight.ServiceReference.FormaPagto fp) {
            return base.Channel.NovaFormaPagtoAsync(fp);
        }
        
        public BlackNight.ServiceReference.FormaPagto[] ListarFormaPagto() {
            return base.Channel.ListarFormaPagto();
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.FormaPagto[]> ListarFormaPagtoAsync() {
            return base.Channel.ListarFormaPagtoAsync();
        }
        
        public BlackNight.ServiceReference.FormaPagto PesquisarFormaPagtoID(string nome) {
            return base.Channel.PesquisarFormaPagtoID(nome);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.FormaPagto> PesquisarFormaPagtoIDAsync(string nome) {
            return base.Channel.PesquisarFormaPagtoIDAsync(nome);
        }
        
        public BlackNight.ServiceReference.FormaPagto PesquisarFormaPagto(int id) {
            return base.Channel.PesquisarFormaPagto(id);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.FormaPagto> PesquisarFormaPagtoAsync(int id) {
            return base.Channel.PesquisarFormaPagtoAsync(id);
        }
        
        public void NovaFormaPagtoVenda(BlackNight.ServiceReference.FormaPagtoVenda fpv) {
            base.Channel.NovaFormaPagtoVenda(fpv);
        }
        
        public System.Threading.Tasks.Task NovaFormaPagtoVendaAsync(BlackNight.ServiceReference.FormaPagtoVenda fpv) {
            return base.Channel.NovaFormaPagtoVendaAsync(fpv);
        }
        
        public BlackNight.ServiceReference.FormaPagtoVenda[] ListarFormaPagtoVenda() {
            return base.Channel.ListarFormaPagtoVenda();
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.FormaPagtoVenda[]> ListarFormaPagtoVendaAsync() {
            return base.Channel.ListarFormaPagtoVendaAsync();
        }
        
        public BlackNight.ServiceReference.FormaPagtoVenda PesquisarFormaPagtoVenda(int id) {
            return base.Channel.PesquisarFormaPagtoVenda(id);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.FormaPagtoVenda> PesquisarFormaPagtoVendaAsync(int id) {
            return base.Channel.PesquisarFormaPagtoVendaAsync(id);
        }
        
        public void NovaAtracao(BlackNight.ServiceReference.Atracao a) {
            base.Channel.NovaAtracao(a);
        }
        
        public System.Threading.Tasks.Task NovaAtracaoAsync(BlackNight.ServiceReference.Atracao a) {
            return base.Channel.NovaAtracaoAsync(a);
        }
        
        public BlackNight.ServiceReference.Atracao PesquisarAtracao(int id) {
            return base.Channel.PesquisarAtracao(id);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Atracao> PesquisarAtracaoAsync(int id) {
            return base.Channel.PesquisarAtracaoAsync(id);
        }
        
        public BlackNight.ServiceReference.Atracao[] ListarAtracoes() {
            return base.Channel.ListarAtracoes();
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Atracao[]> ListarAtracoesAsync() {
            return base.Channel.ListarAtracoesAsync();
        }
        
        public void NovoRitmoEvento(BlackNight.ServiceReference.RitmoEvento re) {
            base.Channel.NovoRitmoEvento(re);
        }
        
        public System.Threading.Tasks.Task NovoRitmoEventoAsync(BlackNight.ServiceReference.RitmoEvento re) {
            return base.Channel.NovoRitmoEventoAsync(re);
        }
        
        public BlackNight.ServiceReference.RitmoEvento PesquisarRitmoEvento(int id) {
            return base.Channel.PesquisarRitmoEvento(id);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.RitmoEvento> PesquisarRitmoEventoAsync(int id) {
            return base.Channel.PesquisarRitmoEventoAsync(id);
        }
        
        public void NovoRitmo(BlackNight.ServiceReference.Ritmo r) {
            base.Channel.NovoRitmo(r);
        }
        
        public System.Threading.Tasks.Task NovoRitmoAsync(BlackNight.ServiceReference.Ritmo r) {
            return base.Channel.NovoRitmoAsync(r);
        }
        
        public BlackNight.ServiceReference.Ritmo PesquisarRitmo(int id) {
            return base.Channel.PesquisarRitmo(id);
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Ritmo> PesquisarRitmoAsync(int id) {
            return base.Channel.PesquisarRitmoAsync(id);
        }
        
        public BlackNight.ServiceReference.Ritmo[] ListarRitmos() {
            return base.Channel.ListarRitmos();
        }
        
        public System.Threading.Tasks.Task<BlackNight.ServiceReference.Ritmo[]> ListarRitmosAsync() {
            return base.Channel.ListarRitmosAsync();
        }
        
        public void ExcluirRitmo(BlackNight.ServiceReference.Ritmo r) {
            base.Channel.ExcluirRitmo(r);
        }
        
        public System.Threading.Tasks.Task ExcluirRitmoAsync(BlackNight.ServiceReference.Ritmo r) {
            return base.Channel.ExcluirRitmoAsync(r);
        }
    }
}
